### ISSUE TITLE
Division by zero in processEimage.py

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#161]
Last night I processed 817 visits through the DM pipeline, and of these 7 failed with float division by zero. The stack trace is:

processEimage.calibrate.measureApCorr: Measuring aperture corrections for 2 flux fields
processEimage.calibrate.measureApCorr: Aperture correction for base_PsfFlux: RMS 0.063219 from 143
Traceback (most recent call last):
  File "/nfs/farm/g/desc/u1/Twinkles/obs_lsstSim/bin/processEimage.py", line 25, in <module>
    ProcessEimageTask.parseAndRun()
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/cmdLineTask.py", line 444, in parseAndRun
    resultList = taskRunner.run(parsedCmd)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/cmdLineTask.py", line 199, in run
    resultList = mapFunc(self, targetList)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/cmdLineTask.py", line 318, in __call__
    result = task.run(dataRef, **kwargs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/nfs/farm/g/desc/u1/Twinkles/obs_lsstSim/python/lsst/obs/lsstSim/processEimage.py", line 123, in run
    result = ProcessCcdTask.run(self, sensorRef)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_tasks/2015_10.0-12-g9f70a69/python/lsst/pipe/tasks/processCcd.py", line 157, in run
    calib = self.calibrate.run(postIsrExposure, idFactory=idFactory, expId=expId)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_tasks/2015_10.0-12-g9f70a69/python/lsst/pipe/tasks/calibrate.py", line 535, in run
    apCorrMap = self.measureApCorr.run(bbox=exposure.getBBox(), catalog=sources).apCorrMap
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/meas_base/2015_10.0-2-gef1b2e0+1/python/lsst/meas/base/measureApCorr.py", line 198, in run
    apCorrData[n] = record.get(self.refFluxKeys.flux)/record.get(keys.flux)
ZeroDivisionError: float division by zero

Full log of a typical failure:

http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/log.jsp?pi=40977122

**Comment by SimonKrughoff** [comment]
That's a real bug.  How do I get the data so I can run it through and debug it?

FYI, I may be able to do some looking next week, but likely won't be able to spend significant time until after the meeting.

**Comment by tony-johnson** [comment]
This particular crash occurred while processing visit 1697655, the phosim data for which can be found here:

/nfs/farm/g/desc/u1/Pipeline-tasks/Twinkles-phoSimII/phosim_output/000840/output

**Comment by tony-johnson** [comment]
@TallJimbo Simon asked me to bring this issue to your attention.

**Comment by jchiang87** [comment]
I filed a ticket for this issue and #162 with DM at  [DM-5758](https://jira.lsstcorp.org/browse/DM-5758).

**Comment by cwwalter** [comment]
Careful!

If you divide by 0 you die: “The Kid Who Learned about Math on the Street by Roz Chast: 

https://t.co/pXMeH1zzhk

**Comment by SimonKrughoff** [comment]
@jchiang87 Thanks for filing that ticket.
