### ISSUE TITLE
Strange failure in processEimage

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#162]
Out of 817 jobs processed last night one failed with:

  File "src/math/LeastSquares.cc", line 434, in void lsst::afw::math::LeastSquares::_factor(bool)
    Number of columns of design matrix (6) must be smaller than number of data points (0) {0}
lsst::pex::exceptions::InvalidParameterError: 'Number of columns of design matrix (6) must be smaller than number of data points (0)'

Full traceback:

processEimage.calibrate.measureApCorr: Measuring aperture corrections for 2 flux fields
processEimage.calibrate.measureApCorr: Aperture correction for base_PsfFlux: RMS 0.033659 from 154
/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/meas_base/2015_10.0-2-gef1b2e0+1/python/lsst/meas/base/measureApCorr.py:213: RuntimeWarning: invalid value encountered in less
  keep = numpy.fabs(apCorrDiffs) < apCorrDiffLim
Traceback (most recent call last):
  File "/nfs/farm/g/desc/u1/Twinkles/obs_lsstSim/bin/processEimage.py", line 25, in <module>
    ProcessEimageTask.parseAndRun()
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/cmdLineTask.py", line 444, in parseAndRun
    resultList = taskRunner.run(parsedCmd)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/cmdLineTask.py", line 199, in run
    resultList = mapFunc(self, targetList)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/cmdLineTask.py", line 318, in __call__
    result = task.run(dataRef, **kwargs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/nfs/farm/g/desc/u1/Twinkles/obs_lsstSim/python/lsst/obs/lsstSim/processEimage.py", line 123, in run
    result = ProcessCcdTask.run(self, sensorRef)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_tasks/2015_10.0-12-g9f70a69/python/lsst/pipe/tasks/processCcd.py", line 157, in run
    calib = self.calibrate.run(postIsrExposure, idFactory=idFactory, expId=expId)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_base/2015_10.0-3-g24e103a+2/python/lsst/pipe/base/timer.py", line 118, in wrapper
    res = func(self, *args, **keyArgs)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/pipe_tasks/2015_10.0-12-g9f70a69/python/lsst/pipe/tasks/calibrate.py", line 535, in run
    apCorrMap = self.measureApCorr.run(bbox=exposure.getBBox(), catalog=sources).apCorrMap
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/meas_base/2015_10.0-2-gef1b2e0+1/python/lsst/meas/base/measureApCorr.py", line 203, in run
    apCorrField = ChebyshevBoundedField.fit(bbox, x, y, apCorrData, ctrl)
  File "/nfs/farm/g/desc/u1/LSST_Stack/lsstsw/stack/Linux64/afw/2015_10.0-8-g4057726/python/lsst/afw/math/mathLib.py", line 9512, in fit
    return _mathLib.ChebyshevBoundedField_fit(*args)
lsst.pex.exceptions.wrappers.InvalidParameterError: 
  File "src/math/LeastSquares.cc", line 434, in void lsst::afw::math::LeastSquares::_factor(bool)
    Number of columns of design matrix (6) must be smaller than number of data points (0) {0}
lsst::pex::exceptions::InvalidParameterError: 'Number of columns of design matrix (6) must be smaller than number of data points (0)'

Full log file:

http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/log.jsp?pi=40977123

**Comment by SimonKrughoff** [comment]
Another bug.  Same question as before, how do I get the data so I can try to repeat?

**Comment by tony-johnson** [comment]
This happened while processing visit 712850, the phosim data for which can be found here:

/nfs/farm/g/desc/u1/Pipeline-tasks/Twinkles-phoSimII/phosim_output/000335/output

**Comment by tony-johnson** [comment]
@TallJimbo Simon asked me to bring this issue to your attention.

**Comment by jchiang87** [comment]
Ticket filed with DM at [DM-5758](https://jira.lsstcorp.org/browse/DM-5758)

**Comment by drphilmarshall** [comment]
Nice! BTW you can now see a record of all the DM tickets we have generated
in [this filtered issue list](
https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues?utf8=%E2%9C%93&q=label%3A%22DM+Ticket%22+).
We are at 3 and counting!

**Comment by jchiang87** [comment]
Some progress at [DM-5758](https://jira.lsstcorp.org/browse/DM-5758):  Paul Price pushed some updates to the corresponding ticket branch of obs_lsstSim that seem to address this issue and #161.  We'll need an update of the Stack in use at SLAC.

**Comment by drphilmarshall** [comment]
Who's taking care of the SLAC Stack update, to bring in Paul's `processEimage.py` bug fixes? There's two closable issues and 10 story points for whoever steps up! :-)

**Comment by jchiang87** [comment]
I've got the Stack installed at /nfs/farm/g/desc/u1/LSST_Stack_2016-04-12 via the conda distribution (thanks @danielsf!  It would be great if I never have to build afw again!)  I would like to close these two issues, but I need to resolve the obs_lsstSim discrepancies between Simon and my different merges of DM-5758 and DM-4302 first.

**Comment by SimonKrughoff** [comment]
I will look this over and merge if I can.

**Comment by jchiang87** [comment]
I've built the current tickets/DM-4302 branch (as of this writing) of obs_lsstSim against the conda distribution.  This and #161 appear to be fixed in that branch.   Closing this and #161.
