### ISSUE TITLE
Photometric and Astrometric Validation of PhoSim runs

### ISSUE THREAD

**Issue by wmwv** [DarkEnergyScienceCollaboration/Twinkles#167]
Compute and analyze overall astrometric and photometric repeatability of Twinkles PhoSim runs as part of Twinkles Run 1.

Tools will include `validate_drp`
https://github.com/lsst/validate_drp

and related tests, such as those @SimonKrughoff did in 
https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/70#issuecomment-168073498

This Issues is not directly looking at lightcurves of known variable objects.  Lightcurve analysis and tests may likely fall more appropriately under Issues for Monitor discussion.

https://github.com/DarkEnergyScienceCollaboration/Monitor

**Comment by wmwv** [comment]
Here are some figures of the astrometric and photometric repeatability as compared to the LSST Science Requirements Document.

u: PA1(IQR) = 82.61+-1.53 mmag
i: PA1(IQR) = 21.95+-1.57 mmag
z: PA1(IQR) = 16.69+-0.57 mmag
y: PA1(IQR) = 25.54+-1.21 mmag

![twinkles_run1_output_i_am1_d_5_arcmin_17 0-21 5](https://cloud.githubusercontent.com/assets/3201257/13550091/7301be60-e2e3-11e5-930a-c9f9ba25259d.png)

![twinkles_run1_output_i_check_photometry](https://cloud.githubusercontent.com/assets/3201257/13550092/7d80f298-e2e3-11e5-8eaf-11db9279f6a1.png)
![twinkles_run1_output_i_pa1](https://cloud.githubusercontent.com/assets/3201257/13550094/8bbbb1c2-e2e3-11e5-89e9-1146f93f9b1e.png)

![twinkles_run1_output_i_check_astrometry](https://cloud.githubusercontent.com/assets/3201257/13550093/82c9ae2a-e2e3-11e5-8440-b77cbddf460e.png)

**Comment by drphilmarshall** [comment]
Cooooooool! Nice work @wmwv :-) I'm going to need many of these panels
unpacking for me, I guess others might be in the same boat. Could I please
ask you to find a good place to put them in our Twinkles session slides
here?:

https://docs.google.com/presentation/d/1MdGGDrITW4-n04goJNYBAoVwnQBjRkibxuJY8EJZWXc/edit#slide=id.p

Real quick: how many visits went into these plots? Which dataset are you
working from?

The script that made these, by calling the validate_drp tools - is it
checked into the Twinkles repo? I'm not tracking commits very well, only
issues and pull requests.

Hooray validation! :-)

**Comment by wmwv** [comment]
These are from just 10 visits from the first sample run of data processing for Twinkles.  My goal today is to understand what has now been processed all the way through processCcd.py (I'm not thinking about coadd stuff yet).  I will update the slides in a few hours with wherever things stand.

These plots and results were generated by simply running:

```
setup validate_drp
validateDrp.py Twinkles/run1/output
```

Where you can install `validate_drp` through the "standard" LSST DM tools (I know they can be frustrating).  For more details see the `validate_drp` repository README.md:
https://github.com/lsst/validate_drp
  or the DM Tech Note at
http://dmtn-008.lsst.io/en/latest/

**Comment by wmwv** [comment]
r-band results from 100-visit run:

![100visits_output_r_am1_d_5_arcmin_17 0-21 5](https://cloud.githubusercontent.com/assets/3201257/13592886/2597d852-e4ab-11e5-80e0-03f10f31e8dd.png)
![100visits_output_r_pa1](https://cloud.githubusercontent.com/assets/3201257/13592887/259ab8ba-e4ab-11e5-8955-81421aa51ebc.png)
![100visits_output_r_check_astrometry](https://cloud.githubusercontent.com/assets/3201257/13592888/25a0bc42-e4ab-11e5-826a-5356736edfd9.png)
![100visits_output_r_check_photometry](https://cloud.githubusercontent.com/assets/3201257/13592889/25a28f22-e4ab-11e5-9616-a02b86a5921d.png)

**Comment by SimonKrughoff** [comment]
Those don't look that great.   Maybe we can chat tomorrow about what might be going on.  Do these plots exclude galaxies by using the classification_extendedness value?

**Comment by drphilmarshall** [comment]
Yeah, lets make sure we leave plenty of time for these. I saw you put a
couple of figures in the slides at
https://docs.google.com/presentation/d/1MdGGDrITW4-n04goJNYBAoVwnQBjRkibxuJY8EJZWXc
, great if you can update them with the most problematic of the new plots!
Thanks Michael, this is great.

**Comment by SimonKrughoff** [comment]
@wmwv and I talked about this a little bit.  I was wrong that they don't show what I expect.  These are more clear than the repeatability figures I've been producing, but the two are consistent.
![image](https://cloud.githubusercontent.com/assets/945715/13644684/f9dd291a-e5db-11e5-9a3b-6449849e99ed.png)

Mostly it was a misinterpretation of the 1.2% floor.  My floor of 10 mmag is similar to that seen by Michael.

**Comment by drphilmarshall** [comment]
@wmwv @TomGlanzman @tony-johnson I have elevated this issue to epic status, and edited the all-important [first comment](https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/167#issue-138712160) to include an initial checklist for what we need to do to get this validation analysis into the workflow and run automagically. No doubt I have done this inadequately, it would be great if you could help improve it. The idea is that each bullet point will point to its own issue - which will also need to be created, and owned - possibly by you! :-)

**Comment by jchiang87** [comment]
@wmwv I'm trying to run the current master of validate_drp on the Run1.1 data (using v12_0_rc1 of the Stack).  I'm seeing this:
```
bash$ validateDrp.py output/
CameraMapper: Loading registry registry from output/_parent/registry.sqlite3
CameraMapper: Loading registry registry from output/_parent/registry.sqlite3
CameraMapper: Loading registry registry from output/_parent/registry.sqlite3
CameraMapper: Loading registry registry from output/_parent/registry.sqlite3
Traceback (most recent call last):
  File "/nfs/farm/g/desc/u1/users/jchiang/desc_projects/twinkles/Run1.1/validate_drp/validate_drp/bin/validateDrp.py", line 86, in <module>
    validate.run(args.repo, **kwargs)
  File "/nfs/farm/g/desc/u1/users/jchiang/desc_projects/twinkles/Run1.1/validate_drp/validate_drp/python/lsst/validate/drp/validate.py", line 460, in run
    **kwargs)
  File "/nfs/farm/g/desc/u1/users/jchiang/desc_projects/twinkles/Run1.1/validate_drp/validate_drp/python/lsst/validate/drp/validate.py", line 525, in runOneFilter
    allMatches = loadAndMatchData(repo, visitDataIds, verbose=verbose)
  File "/nfs/farm/g/desc/u1/users/jchiang/desc_projects/twinkles/Run1.1/validate_drp/validate_drp/python/lsst/validate/drp/validate.py", line 126, in loadAndMatchData
    print(len(oldSrc), "sources in ccd %s  visit %s" % (vId[ccdKeyName], vId["visit"]))
KeyError: 'ccd'
```
Any suggestions?

**Comment by wmwv** [comment]
Yes, `validate_drp` master doesn't work on Twinkles.  I've never successfully integrated the hacks I had to do to get it to work on the LSST simulated.  They're really awful.

There's no general way to get the concept of a 'ccd' from the Butler.  Different cameras use different kesy.  There's 'ccd', 'ccdname', and for LSST camera you need the {'raft', 'sensor'} combination.

**Comment by jchiang87** [comment]
Here are the repeatability numbers 

| filter | PA1(IQR) [mmag] | AM1 [mas] |
|:------:|----------------:|----------:|
| u | 321.16+/-77.44 | 0.00 |
| g | 694.16+/-57.66 | 27.26 |
| r | 563.19+/-38.28 | 26.86 |
| i | 544.99+/-56.31 | 27.75 |

and the plots for i-band:

![output_i_am1_d_5_arcmin_17 0-21 5](https://cloud.githubusercontent.com/assets/1994473/16050592/216c02cc-3211-11e6-809b-1de9502d4f86.png)
![output_i_check_photometry](https://cloud.githubusercontent.com/assets/1994473/16050607/31fc8bb6-3211-11e6-92b8-d3c4213686aa.png)
![output_i_pa1](https://cloud.githubusercontent.com/assets/1994473/16050631/42fbc4f4-3211-11e6-85da-3ad27dabf014.png)
![output_i_check_astrometry](https://cloud.githubusercontent.com/assets/1994473/16050643/4dc9af18-3211-11e6-8ed0-9f217d1d3334.png)

**Comment by wmwv** [comment]
@jchiang87 Ah, yes.  If there's just 1 CCD, your `dataIdFormat={'visit': int}` hack will work.

**Comment by wmwv** [comment]
Hmmm... the photometric repeatability numbers are really bad.

I bet we need to figure out how to separate stars and galaxies much better.

**Comment by wmwv** [comment]
I realize it's worse that star/galaxy separation.  Something just going really funny with the photometry.

**Comment by wmwv** [comment]
I'm investigating this using the files on NERSC in

/global/homes/t/tony_j/Twinkles/Run1.1
(which points to)
/global/cscratch1/sd/tony_j/Twinkles/501

**Comment by wmwv** [comment]
@jchiang87   The NERSC output data repo needs a `_parent` that points to the correct input data repo before the DM Butler can successfully and easily read files.  I've assigned #263 @tony-johnson to fix this.  Once #263 is closed I can take a look further at investigating the repeatibility in this present issue #167.

**Comment by jchiang87** [comment]
Right.  I forgot about that.   To get around this for the db stuff, I created a directory in my area with symlinks so that the butler will work.  That directory is here:
```
/global/u1/j/jchiang8/twinkles/Run1.1
```

**Comment by wmwv** [comment]
Ah, very good solution.

Could you kindly update the permissions so I can use that set of symlinks?

**Comment by jchiang87** [comment]
So I just did this:
```
[edison01] pwd
/global/homes/j/jchiang8/twinkles
[edison01] chmod -R go+rx inputs/
[edison01] chmod -R go+rx Run1.1/
```
Is that sufficient? (It looked to me that you already had access.)

**Comment by wmwv** [comment]
Yes, thank you!

[The previous permissions were:
```
ls -l /global/u1/j/jchiang8/twinkles/
[...]
drwxr-x---  2 jchiang8 jchiang8  4096 Apr 28 10:54 Run1.1
[...]
```
]

**Comment by wmwv** [comment]
@jchiang87 Ran and got the following error message.  Have you seen this before?

I suspect there may be some versioning inconsistency between the obs_lsstSim I have from the 2016-04-15 conda build installed on Cori/Edison.  Will think about how to investigate further.  Suggestions welcome.

```
AttributeError: 'module' object has no attribute 'getKeys'
```

```
[edison02 tmp] validateDrp.py /global/u1/j/jchiang8/twinkles/Run1.1
/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/global/u1/w/wmwv/local/src/validate_drp/bin/validateDrp.py", line 79, in <module>
    kwargs['dataIds'] = util.discoverDataIds(args.repo)
  File "/global/u1/w/wmwv/local/src/validate_drp/python/lsst/validate/drp/util.py", line 147, in discoverDataIds
    thisSubset = butler.subset(datasetType='src', **kwargs)
  File "/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/opt/lsst/daf_persistence/python/lsst/daf/persistence/butler.py", line 425, in subset
    return ButlerSubset(self, datasetType, level, dataId)
  File "/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/opt/lsst/daf_persistence/python/lsst/daf/persistence/butlerSubset.py", line 77, in __init__
    keys = self.butler.getKeys(datasetType, level)
  File "/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/opt/lsst/daf_persistence/python/lsst/daf/persistence/butler.py", line 232, in getKeys
    return self.repository.getKeys(datasetType, level)
  File "/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/opt/lsst/daf_persistence/python/lsst/daf/persistence/repository.py", line 361, in getKeys
    return self.doParents(Repository.doGetKeys, *args, **kwargs)
  File "/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/opt/lsst/daf_persistence/python/lsst/daf/persistence/repository.py", line 325, in doParents
    res = func(parent, *args, **kwargs)
  File "/project/projectdirs/lsst/lsstDM/Cori/conda-env/2016-04-15/LSST_STACK/opt/lsst/daf_persistence/python/lsst/daf/persistence/repository.py", line 374, in doGetKeys
    return self._mapper.getKeys(*args, **kwargs)
AttributeError: 'module' object has no attribute 'getKeys'
```

**Comment by jchiang87** [comment]
No, I didn't see that error running with v12_0_rc1.  I have a conda install of the Stack of the same vintage at slac.  I'll try with that Stack to see if I get the same error.

**Comment by jchiang87** [comment]
Using the conda distribution I installed at SLAC on 2016-04-12, everything seems to be working fine for `validateDrp.py`.  It finished g-band and is working the next one.  Here is some provenance info on that Stack:
```
bash-4.1$ eups list lsst_apps
   w.2016.15    current b2003 conda setup
bash-4.1$ 
```

**Comment by SimonKrughoff** [comment]
@wmwv That is very strange.  That very line is still in [master](https://github.com/lsst/daf_persistence/blob/eb625e2edb7caae8c833f3e578a2316062a3d090/python/lsst/daf/persistence/repository.py#L374).

**Comment by jchiang87** [comment]
Here is the contents of `_mapper`:
```
[edison12] cat _parent/_mapper 
lsst.obs.lsstSim.LsstSimMapper
[edison12] 
```
BTW, that output repo worked fine for the `pserv` ingest (which uses the butler to find the files) into the DESC_Twinkles_Level2 db.  For that, I used the most recent Stack that Heather installed for cori.

**Comment by wmwv** [comment]
@SimonKrughoff @jchiang87   Apologies!  Problem existed between keyboard and chair!

**Comment by tony-johnson** [comment]
@wmwv Can this issue be closed, or is it still active? Moving to "Post Run 2 tasks for now".
