### ISSUE TITLE
New failure mode in completeCoadd

### ISSUE THREAD

**Issue by tony-johnson** [DarkEnergyScienceCollaboration/Twinkles#226]
I reran the TwinklesDM workflow using /nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/ install of DM. It worked until the complete coadd stage which failed with after 8657 second of CPU with:

measureCoaddSources.measurement.applyApCorr: Applying aperture corrections to 2 flux fields
measureCoaddSources.measurement.applyApCorr: Use naive flux sigma computation
measureCoaddSources.measurement: Measuring 43686 sources (17202 parents, 26484 children) 
measureCoaddSources.setPrimaryFlags WARNING: merge_peak is not set for pseudo-filter sky
measureCoaddSources.propagateFlags: Propagating flags ['calib_psfCandidate', 'calib_psfUsed'] from inputs
Traceback (most recent call last):
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/pipe_tasks/2016_01.0-8-g428dafe+3/bin/measureCoaddSources.py", line 3, in <module>
    MeasureMergedCoaddSourcesTask.parseAndRun()
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/pipe_base/2016_01.0+19/python/lsst/pipe/base/cmdLineTask.py", line 444, in parseAndRun
    resultList = taskRunner.run(parsedCmd)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/pipe_base/2016_01.0+19/python/lsst/pipe/base/cmdLineTask.py", line 199, in run
    resultList = mapFunc(self, targetList)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/pipe_base/2016_01.0+19/python/lsst/pipe/base/cmdLineTask.py", line 318, in __call__
    result = task.run(dataRef, **kwargs)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/pipe_tasks/2016_01.0-8-g428dafe+3/python/lsst/pipe/tasks/multiBand.py", line 650, in run
    exposure.getWcs())
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/pipe_tasks/2016_01.0-8-g428dafe+3/python/lsst/pipe/tasks/propagateVisitFlags.py", line 182, in run
    ccdSources = butler.get("icSrc", visit=int(v), ccd=int(c), immediate=True)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/daf_persistence/2016_01.0-2-g3878625+3/python/lsst/daf/persistence/butler.py", line 259, in get
    location = self.mapper.map(datasetType, dataId)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/daf_persistence/2016_01.0-2-g3878625+3/python/lsst/daf/persistence/mapper.py", line 116, in map
    return func(self.validate(dataId), write)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/daf_butlerUtils/2016_01.0+16/python/lsst/daf/butlerUtils/cameraMapper.py", line 281, in mapClosure
    return mapping.map(mapper, dataId, write)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/daf_butlerUtils/2016_01.0+16/python/lsst/daf/butlerUtils/mapping.py", line 123, in map
    actualId = self.need(self.keyDict.iterkeys(), dataId)
  File "/nfs/farm/g/desc/u1/LSST_Stack_2016-02-23/lsstsw/stack/Linux64/daf_butlerUtils/2016_01.0+16/python/lsst/daf/butlerUtils/mapping.py", line 210, in need
    (newProps, newId, len(lookups))
RuntimeError: No unique lookup for ['filter', 'raft', 'sensor'] from {'ccd': 2211, 'visit': 222588}: 0 matches

@jchiang87 @SimonKrughoff I don't know if this is worth reporting to DM, maybe we should wait and see if the same error occurs with the next software update.

Log file: http://srs.slac.stanford.edu/Pipeline-II/exp/SRS/log.jsp?pi=41539864

Workflow: http://srs.slac.stanford.edu/Pipeline-II/exp/SRS/si.jsp?stream=41535760

Output: /nfs/slac/kipac/fs1/g/desc/Twinkles/402

**Comment by SimonKrughoff** [comment]
@tony-johnson unless the markdown munged your text, there was a problem with the command line you ran.  There is no such thing as ccd 2211.  I'm not sure there should be a ccd key in there at all.

**Comment by tony-johnson** [comment]
The command line was just:

measureCoaddSources.py /gpfs/slac/kipac/fs1/g/desc/Twinkles/402 --id tract=0 patch=0,0 'filter=u^g^r^i^z^y' --config measurement.doApplyApCorr=yes --doraise --clobber-config

(see https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/workflows/DM/completeCoadd). I do not know where ccd 2211 came from?

**Comment by SimonKrughoff** [comment]
Yes.  Looking further, there is a bug.  I'll look into it.

**Comment by SimonKrughoff** [comment]
I've turned this off in DM-4302, so when that is merged, it should take care of this.

**Comment by SimonKrughoff** [comment]
DM-4302 was merged with the latest version of the stack I installed.  @tony-johnson can you confirm that this went away?

**Comment by tony-johnson** [comment]
Yes this went away with the latest version of the stack. Closing issue.

**Comment by drphilmarshall** [comment]
W00t!
