### ISSUE TITLE
MemoryError from generatePhosimInputs.py script

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/Twinkles#338]
@rbiswas4 @danielsf I'm trying the new `generatePhosimInputs.py` script from #327 using the `w.2016.40-sims_2.3.1` sims Stack that @heather999 just installed at SLAC.   When I run the script, it starts out ok and writes the `starCat` objects ok, but then it stalled for 10-15 minutes while trying to write `galCat`, and finally ended with a memory error.   I've inserted below the full screen output.

Any suggestions?

```
$ generatePhosimInput.py 200
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 25 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 40 specified: 
[Twinkles] ./run_generatePhosimInput.sh 
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 25 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py:439: UserWarning: Duplicate object type id 40 specified: 
Output object ids may not be unique.
This may not be a problem if you do not want globally unique id values
  'want globally unique id values')
will generate pointing for 200 and write to filename ./phosim_input_200.txt
{'mjd': 59580.123742999996, 'pointingRA': 56.520281137372756, 'rotSkyPos': 356.35786158359804, 'boundLength': 0.29999999999999999, 'skyBrightness': 17.300000000000001, 'OpsimMetaData': {'sunAlt': -0.53665799999999997, 'sunAz': 3.6504340000000002, 'rotSkyPos': 6.2196179999999996, 'slewDist': 0.049426999999999999, 'mieScatter': 8038.6125940000002, 'moonIllum': 7.1000000000000005e-05, 'visitExpTime': 30.0, 'lst': 1.3011459999999999, 'azimuth': 3.3564919999999998, 'moonDec': -0.409327, 'humidity': 0.0, 'ditheredRA': 0.94963807402972034, 'moonPhase': 3.893519, 'phaseAngle': 157.23943199999999, 'index': 0, 'filtSkyBrightness': 17.300000000000001, 'rawSeeing': 0.74412, 'altitude': 0.92568300000000003, 'fieldRA': 0.98646500000000004, 'rotTelPos': 0.39675199999999999, 'obsHistID': 200, 'moonAlt': -0.633266, 'solarElong': 85.061981000000003, 'moonRA': 4.4690029999999998, 'FWHMeff': 0.98029299999999997, 'airmass': 1.2515179999999999, 'expMJD': 59580.123742999996, 'night': 0, 'darkBright': 94.164088000000007, 'expDate': 10691, 'moonBright': 0.0, 'finRank': 4.5418089999999998, 'dist2Moon': 1.5671790000000001, 'propID': 53, 'moonAZ': 3.171484, 'FWHMgeom': 0.85780100000000004, 'rScatter': 242834.96840000001, 'fieldDec': -1.143187, 'sessionID': 1016, 'ditheredDec': -1.169638, 'visitTime': 34.0, 'filter': u'y', 'fiveSigmaDepth': 21.483129999999999, 'slewTime': 4.5217070000000001, 'transparency': 0.0, 'vSkyBright': 21.396433999999999, 'fieldID': 244, 'wind': 0.0}, 'site': <lsst.sims.utils.Site.Site object at 0x7f1a1e5e0510>, 'boundType': 'circle', 'bandpass': u'y', 'pointingDec': -65.499790294222038}
writing starCat 
WARNING: ErfaWarning: ERFA function "taiutc" yielded 1 of "dubious year (Note 4)" [astropy._erfa.core]
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_utils/12.0-10-ged4de25+4/python/lsst/sims/utils/ModifiedJulianDate.py:188: UTCtoUT1Warning: UTC is outside of IERS table for UT1-UTC.
Returning UT1 = UTC for lack of a better idea
This warning was caused by calling ModifiedJulianDate.dut1

  category=UTCtoUT1Warning)
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sqlalchemy/1.0.8.lsst3+2/lib/python/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/dialects/mssql/base.py:1783: SAWarning: Did not recognize type 'geography' of column 'geopoint'
  (type, name))
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_utils/12.0-10-ged4de25+4/python/lsst/sims/utils/ModifiedJulianDate.py:188: UTCtoUT1Warning: UTC is outside of IERS table for UT1-UTC.
Returning UT1 = UTC for lack of a better idea
This warning was caused by calling ModifiedJulianDate.UT1

  category=UTCtoUT1Warning)
/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sqlalchemy/1.0.8.lsst3+2/lib/python/SQLAlchemy-1.0.8-py2.7-linux-x86_64.egg/sqlalchemy/sql/elements.py:3779: SAWarning: Textual SQL expression 'gmag > 11.0' should be explicitly declared as text('gmag > 11.0') (this warning may be suppressed after 10 occurrences)
  {"expr": util.ellipses_string(element)})
writing galCat
Traceback (most recent call last):
  File "/nfs/farm/g/desc/u1/twinkles/Twinkles/bin/generatePhosimInput.py", line 138, in <module>
    sn_sed_file_dir=sn_sed_file_dir)
  File "/nfs/farm/g/desc/u1/twinkles/Twinkles/bin/generatePhosimInput.py", line 78, in generateSinglePointing
    tSky.writePhoSimCatalog(fname)
  File "/nfs/farm/g/desc/u1/twinkles/Twinkles/python/desc/twinkles/twinkles_sky.py", line 146, in writePhoSimCatalog
    write_header=False)
  File "/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/definitions/CompoundInstanceCatalog.py", line 297, in write_catalog
    write_mode=write_mode)
  File "/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/definitions/CompoundInstanceCatalog.py", line 352, in _write_compound
    for chunk in master_results:
  File "/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py", line 70, in next
    return self._postprocess_results(chunk)
  File "/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py", line 83, in _postprocess_results
    return self.dbobj._postprocess_results(chunk)
  File "/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/DMstack/w.2016.40-sims_2.3.1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.py", line 692, in _postprocess_results
    retresults = numpy.rec.fromrecords(results_array, dtype=dtype)
  File "/nfs/farm/g/lsst/u1/software/redhat6-x86_64-64bit-gcc44/anaconda/py-2.7.11/lib/python2.7/site-packages/numpy/core/records.py", line 671, in fromrecords
    retval = sb.array(recList, dtype=descr)
MemoryError
```

**Comment by rbiswas4** [comment]
@jchiang87 
We may want a `chunksize`  parameter in 
```
       galCat.write_catalog(fileName, write_mode='a',
                               write_header=False)
```
so we could change that to 
```
galCat.write_catalog(fileName, write_mode='a', chunksize=10000,
                                   write_header=False)
```
We had experimented with this before, and it seemed to work faster without the chunksize for me, but my laptop has a large amount of memory, so we should probably re-insert this.

**Comment by jchiang87** [comment]
I made the change on my copy (using `chunk_size` though) and it worked.  I also switched to a machine with more memory, so the ultimate fix is uncertain, but nonetheless, I think we should include this change.  I'll make a note at the PR.
